libname final "/home/u60712753/sasuser.v94/fin 580/final";


data return1;
set final.return;
YEAR=year(DATADATE);
MONTH=month(DATADATE);
drop DATADATE;
run;

proc sort data=return1 out=return2;
by TIC YEAR MONTH;
run;

data return3;
set return2;
where TRT1M is not missing;
run;

proc freq data=return3;
tables TIC*YEAR/NOPERCENT NOROW NOCOL;
run;

data return4;
set return3;
where TIC ^='3CCIKO' and TIC ^='4741B' and TIC ^='AEPPL' and TIC ^='AEPPZ' and TIC ^='AESC' and TIC ^='AMCO30' and TIC ^='AMCR' and TIC ^='ANET' and TIC ^='ANTX.2' and TIC ^='BKR' and TIC ^='CARR' and TIC ^='CDAY' and TIC ^='CDAY.' and TIC ^='CDW' and TIC ^='CFG' and TIC ^='CTLT' and TIC ^='CTVA' and TIC ^='CUKPF' and TIC ^='CZR' and TIC ^='DOV.WI' and TIC ^='DOW' and TIC ^='DTP' and TIC ^='ENPH' and TIC ^='ETSY' and TIC ^='FB' and TIC ^='FOX' and TIC ^='FOXA' and TIC ^='FTV' and TIC ^='GDI.2' and TIC ^='GOOG' and TIC ^='HNZ' and TIC ^='HPE' and TIC ^='HWM' and TIC ^='IFFT' and TIC ^='IQV' and TIC ^='IR' and TIC ^='JCI.PZ' and TIC ^='KEYS' and TIC ^='KHC' and TIC ^='LW' and TIC ^='MRK.WI' and TIC ^='NCLH' and TIC ^='NEE.PO' and TIC ^='NEE.PP' and TIC ^='NEE.PQ' and TIC ^='NEE.PQ.1' and TIC ^='NGT.' and TIC ^='NOW' and TIC ^='NWS' and TIC ^='NWSA' and TIC ^='OGN' and TIC ^='PSA.PB' and TIC ^='PSX' and TIC ^='PYPL' and TIC ^='SOLN' and TIC ^='SWT' and TIC ^='SYF' and TIC ^='TMUS' and TIC ^='USB.PA' and TIC ^='USB.PQ' and TIC ^='USB.PA' and TIC ^='OTIS' and TIC ^='PAYC' and TIC ^='UA' and TIC ^='ZTS';
run;

proc freq data=return4;
tables TIC*YEAR/NOPERCENT NOROW NOCOL;
run;

proc sort data=return4;
by TIC YEAR MONTH;
run; 

data return5;
set return4;
by TIC YEAR;
if first.year=1 then CUMRETURN=0;
CUMRETURN+TRT1M;
if last.year=1;
run;

data return6;
set return5;
drop month;
where YEAR^=2022;
run;

data return7;
set return6;
YEAR=YEAR-1;
drop GVKEY IID TRT1M;
run;

proc freq data=final.fundamental;
tables TIC*FYEAR/NOPERCENT NOROW NOCOL;
run;

proc sort data=final.fundamental out=fundamental1 NODUPKEY;
by TIC FYEAR;
run;

proc freq data=fundamental1;
tables TIC*FYEAR/NOPERCENT NOROW NOCOL;
run;

data fundamental2;
set fundamental1;
where ACT is not missing and CH is not missing and LCT is not missing and MIB is not missing and PPENT is not missing and PSTK is not missing and EBIT is not missing and DT is not missing and MKVALT is not missing;
run;

data fundamental3;
set fundamental2;
Capital=PPENT+ACT-LCT;
TEV=MKVALT+DT+PSTK+MIB-CH-ACT+LCT;
run;

data fundamental4;
set fundamental3;
ROC=EBIT/Capital;
EY=EBIT/TEV;
keep TIC FYEAR SICH EY ROC;
rename FYEAR=YEAR;
run;

proc sort data=fundamental4;
by TIC YEAR;
run;
proc sort data=return7;
by TIC YEAR;
run;

data complete1;
merge fundamental4(in=x) return7(in=y);
by TIC YEAR;
if x=1 and y=1;
run;
proc freq data=complete1;
tables TIC*YEAR/nocol norow nopercent;
run;
proc sort data=complete1 out=complete2;
by YEAR descending ROC;
run;
data complete3;
set complete2;
by YEAR;
if first.year=1 then ROCSORT=0;
ROCSORT+1;
drop EY;
run;
proc sort data=complete1 out=complete4;
by YEAR descending EY;
run;
data complete5;
set complete4;
by YEAR;
if first.year=1 then EYSORT=0;
EYSORT+1;
drop ROC;
run;
proc sort data=complete3;
by TIC YEAR;
run;
proc sort data=complete5;
by TIC YEAR;
run;
data final1;
merge complete3 complete5;
by TIC YEAR;
Rank=ROCSORT+EYSORT;
drop ROCSORT EYSORT;
run;
proc freq data=final1;
tables YEAR;
run;


data return1;
set final.return;
YEAR=year(DATADATE);
MONTH=month(DATADATE);
drop DATADATE;
run;
proc sort data=return1 out=return2;
by TIC YEAR MONTH;
run;
data return3;
set return2;
where TRT1M is not missing;
run;
proc freq data=return3;
tables TIC*YEAR/NOPERCENT NOROW NOCOL;
run;
data return4;
set return3;
where TIC ^='3CCIKO' and TIC ^='4741B' and TIC ^='AEPPL' and TIC ^='AEPPZ' and TIC ^='AESC' and TIC ^='AMCO30' and TIC ^='AMCR' and TIC ^='ANET' and TIC ^='ANTX.2' and TIC ^='BKR' and TIC ^='CARR' and TIC ^='CDAY' and TIC ^='CDAY.' and TIC ^='CDW' and TIC ^='CFG' and TIC ^='CTLT' and TIC ^='CTVA' and TIC ^='CUKPF' and TIC ^='CZR' and TIC ^='DOV.WI' and TIC ^='DOW' and TIC ^='DTP' and TIC ^='ENPH' and TIC ^='ETSY' and TIC ^='FB' and TIC ^='FOX' and TIC ^='FOXA' and TIC ^='FTV' and TIC ^='GDI.2' and TIC ^='GOOG' and TIC ^='HNZ' and TIC ^='HPE' and TIC ^='HWM' and TIC ^='IFFT' and TIC ^='IQV' and TIC ^='IR' and TIC ^='JCI.PZ' and TIC ^='KEYS' and TIC ^='KHC' and TIC ^='LW' and TIC ^='MRK.WI' and TIC ^='NCLH' and TIC ^='NEE.PO' and TIC ^='NEE.PP' and TIC ^='NEE.PQ' and TIC ^='NEE.PQ.1' and TIC ^='NGT.' and TIC ^='NOW' and TIC ^='NWS' and TIC ^='NWSA' and TIC ^='OGN' and TIC ^='PSA.PB' and TIC ^='PSX' and TIC ^='PYPL' and TIC ^='SOLN' and TIC ^='SWT' and TIC ^='SYF' and TIC ^='TMUS' and TIC ^='USB.PA' and TIC ^='USB.PQ' and TIC ^='USB.PA' and TIC ^='OTIS' and TIC ^='PAYC' and TIC ^='UA' and TIC ^='ZTS';
run;
proc freq data=return4;
tables TIC*YEAR/NOPERCENT NOROW NOCOL;
run;
proc sort data=return4;
by TIC YEAR MONTH;
run; 
data return5;
set return4;
by TIC YEAR;
if first.year=1 then CUMRETURN=0;
CUMRETURN+TRT1M;
if last.year=1;
run;
data return6;
set return5;
drop month;
where YEAR^=2022;
run;
data return7;
set return6;
YEAR=YEAR-1;
drop GVKEY IID TRT1M;
run;
proc freq data=final.fundamental;
tables TIC*FYEAR/NOPERCENT NOROW NOCOL;
run;
proc sort data=final.fundamental out=fundamental1 NODUPKEY;
by TIC FYEAR;
run;
proc freq data=fundamental1;
tables TIC*FYEAR/NOPERCENT NOROW NOCOL;
run;
data fundamental2;
set fundamental1;
where ACT is not missing and CH is not missing and LCT is not missing and MIB is not missing and PPENT is not missing and PSTK is not missing and EBIT is not missing and DT is not missing and MKVALT is not missing;
run;
data fundamental3;
set fundamental2;
Capital=PPENT+ACT-LCT;
TEV=MKVALT+DT+PSTK+MIB-CH-ACT+LCT;
run;
data fundamental4;
set fundamental3;
ROC=EBIT/Capital;
EY=EBIT/TEV;
keep TIC FYEAR SICH EY ROC;
rename FYEAR=YEAR;
run;
proc sort data=fundamental4;
by TIC YEAR;
run;
proc sort data=return7;
by TIC YEAR;
run;
data complete1;
merge fundamental4(in=x) return7(in=y);
by TIC YEAR;
if x=1 and y=1;
run;
proc freq data=complete1;
tables TIC*YEAR/nocol norow nopercent;
run;
proc sort data=complete1 out=complete2;
by YEAR descending ROC;
run;
data complete3;
set complete2;
by YEAR;
if first.year=1 then ROCSORT=0;
ROCSORT+1;
drop EY;
run;
proc sort data=complete1 out=complete4;
by YEAR descending EY;
run;
data complete5;
set complete4;
by YEAR;
if first.year=1 then EYSORT=0;
EYSORT+1;
drop ROC;
run;
proc sort data=complete3;
by TIC YEAR;
run;
proc sort data=complete5;
by TIC YEAR;
run;
data final1;
merge complete3 complete5;
by TIC YEAR;
Rank=ROCSORT+EYSORT;
drop ROCSORT EYSORT;
run;
proc freq data=final1;
tables YEAR;
run;
data final20111;
set final1;
where YEAR=2011;
run;
proc sort data=final20111 out=final20112;
by Rank;
run;
data final2011;
set final20112(firstobs=1 obs=4);  
run;
data final20121;
set final1;
where YEAR=2012;
run;
proc sort data=final20121 out=final20122;
by Rank;
run;
data final2012;
set final20122(firstobs=1 obs=33);  
run;
data final20131;
set final1;
where YEAR=2013;
run;
proc sort data=final20131 out=final20132;
by Rank;
run;
data final2013;
set final20132(firstobs=1 obs=33);  
run;
data final20141;
set final1;
where YEAR=2014;
run;
proc sort data=final20141 out=final20142;
by Rank;
run;
data final2014;
set final20142(firstobs=1 obs=33);  
run;
data final20151;
set final1;
where YEAR=2015;
run;
proc sort data=final20151 out=final20152;
by Rank;
run;
data final2015;
set final20152(firstobs=1 obs=33);  
run;
data final20161;
set final1;
where YEAR=2016;
run;
proc sort data=final20161 out=final20162;
by Rank;
run;
data final2016;
set final20162(firstobs=1 obs=33);  
run;
data final20171;
set final1;
where YEAR=2017;
run;
proc sort data=final20171 out=final20172;
by Rank;
run;
data final2017;
set final20172(firstobs=1 obs=33);  
run;
data final20181;
set final1;
where YEAR=2018;
run;
proc sort data=final20181 out=final20182;
by Rank;
run;
data final2018;
set final20182(firstobs=1 obs=33);  
run;
data final20191;
set final1;
where YEAR=2019;
run;
proc sort data=final20191 out=final20192;
by Rank;
run;
data final2019;
set final20192(firstobs=1 obs=33);  
run;
data final20201;
set final1;
where YEAR=2020;
run;
proc sort data=final20201 out=final20202;
by Rank;
run;
data final2020;
set final20202(firstobs=1 obs=33);  
run;
data final2;
set final2011 final2012 final2013 final2014 final2015 final2016 final2017 final2018 final2019 final2020;
run;
proc means data=final2 mean;
var CUMRETURN;
class YEAR;
ways 1;
output out=final3 mean=INVESTMENT_RETURN;
run;
data final4;
set final3;
INVESTMENT_CUMRETURN+INVESTMENT_RETURN;
drop _TYPE_ _FREQ_;
YEAR=YEAR+1;
run;
proc import datafile='/home/u60719338/final/SP500.xlsx'
dbms=xlsx out=final.SP500;
run;
proc sort data=final4;
by YEAR;
run;
proc sort data=final.sp500;
by YEAR;
run;
data finalresult;
merge final4 final.sp500;
by YEAR;
RETURN_DIFFERENCE=INVESTMENT_RETURN-SP500_RETURN;
CUMRETURN_DIFFERENCE=INVESTMENT_CUMRETURN-SP500_CUMRETURN;
run;
